import type { Product, Brand, Category } from "./types"

export const brands: Brand[] = [
  { id: "1", name: "Honda", slug: "honda", logo: "/honda-motorcycle-logo.jpg" },
  { id: "2", name: "Yamaha", slug: "yamaha", logo: "/yamaha-motorcycle-logo.jpg" },
  { id: "3", name: "Suzuki", slug: "suzuki", logo: "/suzuki-motorcycle-logo.jpg" },
  { id: "4", name: "Kawasaki", slug: "kawasaki", logo: "/kawasaki-motorcycle-logo.jpg" },
  { id: "5", name: "BMW", slug: "bmw", logo: "/bmw-motorcycle-logo.jpg" },
  { id: "6", name: "KTM", slug: "ktm", logo: "/ktm-motorcycle-logo.jpg" },
  { id: "7", name: "Ducati", slug: "ducati", logo: "/ducati-motorcycle-logo.jpg" },
  { id: "8", name: "Triumph", slug: "triumph", logo: "/triumph-motorcycle-logo.jpg" },
]

export const categories: Category[] = [
  {
    id: "1",
    name: "Motor Parçaları",
    slug: "motor-parcalari",
    image: "/motorcycle-engine-parts.png",
    children: [
      { id: "1-1", name: "Piston & Segman", slug: "piston-segman", parentId: "1" },
      { id: "1-2", name: "Silindir", slug: "silindir", parentId: "1" },
      { id: "1-3", name: "Krank Mili", slug: "krank-mili", parentId: "1" },
      { id: "1-4", name: "Supap", slug: "supap", parentId: "1" },
    ],
  },
  {
    id: "2",
    name: "Fren Sistemi",
    slug: "fren-sistemi",
    image: "/motorcycle-brake-system.jpg",
    children: [
      { id: "2-1", name: "Fren Balatası", slug: "fren-balatasi", parentId: "2" },
      { id: "2-2", name: "Fren Diski", slug: "fren-diski", parentId: "2" },
      { id: "2-3", name: "Fren Kaliperi", slug: "fren-kaliperi", parentId: "2" },
    ],
  },
  {
    id: "3",
    name: "Elektrik & Aydınlatma",
    slug: "elektrik-aydinlatma",
    image: "/motorcycle-electrical-parts.jpg",
    children: [
      { id: "3-1", name: "Far", slug: "far", parentId: "3" },
      { id: "3-2", name: "Sinyal", slug: "sinyal", parentId: "3" },
      { id: "3-3", name: "Akü", slug: "aku", parentId: "3" },
    ],
  },
  {
    id: "4",
    name: "Şanzıman & Aktarma",
    slug: "sanziman-aktarma",
    image: "/motorcycle-transmission.png",
    children: [
      { id: "4-1", name: "Debriyaj", slug: "debriyaj", parentId: "4" },
      { id: "4-2", name: "Zincir & Dişli", slug: "zincir-disli", parentId: "4" },
    ],
  },
  {
    id: "5",
    name: "Süspansiyon",
    slug: "suspansiyon",
    image: "/motorcycle-suspension.jpg",
  },
  {
    id: "6",
    name: "Filtreler",
    slug: "filtreler",
    image: "/motorcycle-filters.jpg",
    children: [
      { id: "6-1", name: "Hava Filtresi", slug: "hava-filtresi", parentId: "6" },
      { id: "6-2", name: "Yağ Filtresi", slug: "yag-filtresi", parentId: "6" },
      { id: "6-3", name: "Yakıt Filtresi", slug: "yakit-filtresi", parentId: "6" },
    ],
  },
  {
    id: "7",
    name: "Kaporta & Plastik",
    slug: "kaporta-plastik",
    image: "/motorcycle-fairings.jpg",
  },
  {
    id: "8",
    name: "Aksesuar",
    slug: "aksesuar",
    image: "/motorcycle-accessories.png",
  },
]

export const products: Product[] = [
  {
    id: "1",
    sku: "MP-001",
    oem: "06455-KYJ-841",
    name: "Honda CBR250R Ön Fren Balatası",
    slug: "honda-cbr250r-on-fren-balatasi",
    description: "Orijinal kalitesinde ön fren balatası. Yüksek performanslı fren deneyimi için tasarlanmıştır.",
    price: 450,
    discountPrice: 399,
    stock: 25,
    images: ["/motorcycle-brake-pad-front.jpg", "/motorcycle-brake-pad-detail.jpg"],
    brand: brands[0],
    category: categories[1],
    compatibility: [
      { brand: "Honda", model: "CBR250R", yearStart: 2011, yearEnd: 2023 },
      { brand: "Honda", model: "CB300F", yearStart: 2015, yearEnd: 2023 },
    ],
    weight: 0.3,
    dimensions: { width: 10, height: 8, depth: 2 },
    tags: ["fren", "balata", "honda", "cbr250r"],
    isActive: true,
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2",
    sku: "MP-002",
    oem: "5VY-11631-00",
    name: "Yamaha YZF-R6 Piston Kiti",
    slug: "yamaha-yzf-r6-piston-kiti",
    description: "Yüksek performanslı piston kiti. Segman ve perno dahildir.",
    price: 1850,
    stock: 8,
    images: ["/placeholder.svg?height=400&width=400", "/placeholder.svg?height=400&width=400"],
    brand: brands[1],
    category: categories[0],
    compatibility: [{ brand: "Yamaha", model: "YZF-R6", yearStart: 2006, yearEnd: 2020, engineType: "600cc" }],
    weight: 0.8,
    dimensions: { width: 12, height: 12, depth: 8 },
    tags: ["piston", "motor", "yamaha", "r6"],
    isActive: true,
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "3",
    sku: "MP-003",
    oem: "13780-44G00",
    name: "Suzuki GSX-R750 Hava Filtresi",
    slug: "suzuki-gsx-r750-hava-filtresi",
    description: "Orijinal spesifikasyonda hava filtresi. Motorunuzun nefes almasını sağlar.",
    price: 320,
    discountPrice: 279,
    stock: 42,
    images: ["/placeholder.svg?height=400&width=400"],
    brand: brands[2],
    category: categories[5],
    compatibility: [
      { brand: "Suzuki", model: "GSX-R750", yearStart: 2006, yearEnd: 2023 },
      { brand: "Suzuki", model: "GSX-R600", yearStart: 2006, yearEnd: 2023 },
    ],
    weight: 0.2,
    dimensions: { width: 25, height: 20, depth: 5 },
    tags: ["filtre", "hava filtresi", "suzuki", "gsxr"],
    isActive: true,
    isFeatured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "4",
    sku: "MP-004",
    oem: "92057-0125",
    name: "Kawasaki Ninja 650 Zincir Dişli Seti",
    slug: "kawasaki-ninja-650-zincir-disli-seti",
    description: "Komple zincir ve dişli seti. 520 pitch, 114 bakla.",
    price: 1250,
    stock: 15,
    images: ["/placeholder.svg?height=400&width=400", "/placeholder.svg?height=400&width=400"],
    brand: brands[3],
    category: categories[3],
    compatibility: [
      { brand: "Kawasaki", model: "Ninja 650", yearStart: 2012, yearEnd: 2023 },
      { brand: "Kawasaki", model: "Z650", yearStart: 2017, yearEnd: 2023 },
    ],
    weight: 2.5,
    dimensions: { width: 30, height: 30, depth: 10 },
    tags: ["zincir", "dişli", "kawasaki", "ninja"],
    isActive: true,
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "5",
    sku: "MP-005",
    oem: "34327726780",
    name: "BMW R1200GS Debriyaj Seti",
    slug: "bmw-r1200gs-debriyaj-seti",
    description: "Premium kalite debriyaj seti. Baskı plakası ve balata dahil.",
    price: 3200,
    discountPrice: 2899,
    stock: 5,
    images: ["/placeholder.svg?height=400&width=400"],
    brand: brands[4],
    category: categories[3],
    compatibility: [
      { brand: "BMW", model: "R1200GS", yearStart: 2013, yearEnd: 2018 },
      { brand: "BMW", model: "R1200RT", yearStart: 2014, yearEnd: 2018 },
    ],
    weight: 1.8,
    dimensions: { width: 25, height: 25, depth: 8 },
    tags: ["debriyaj", "bmw", "r1200gs"],
    isActive: true,
    isFeatured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "6",
    sku: "MP-006",
    oem: "75015090000",
    name: "KTM Duke 390 LED Far Seti",
    slug: "ktm-duke-390-led-far-seti",
    description: "Yüksek parlaklıkta LED far seti. Gece sürüşlerinde mükemmel görüş.",
    price: 2100,
    stock: 12,
    images: ["/placeholder.svg?height=400&width=400", "/placeholder.svg?height=400&width=400"],
    brand: brands[5],
    category: categories[2],
    compatibility: [
      { brand: "KTM", model: "Duke 390", yearStart: 2017, yearEnd: 2023 },
      { brand: "KTM", model: "RC 390", yearStart: 2017, yearEnd: 2023 },
    ],
    weight: 0.6,
    dimensions: { width: 20, height: 15, depth: 15 },
    tags: ["far", "led", "aydınlatma", "ktm"],
    isActive: true,
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "7",
    sku: "MP-007",
    oem: "43611091A",
    name: "Ducati Monster 821 Ön Amortisör",
    slug: "ducati-monster-821-on-amortisor",
    description: "Yüksek performanslı ön amortisör. Ayarlanabilir sönümleme.",
    price: 4500,
    stock: 3,
    images: ["/placeholder.svg?height=400&width=400"],
    brand: brands[6],
    category: categories[4],
    compatibility: [{ brand: "Ducati", model: "Monster 821", yearStart: 2014, yearEnd: 2020 }],
    weight: 5.2,
    dimensions: { width: 15, height: 80, depth: 15 },
    tags: ["amortisör", "süspansiyon", "ducati", "monster"],
    isActive: true,
    isFeatured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "8",
    sku: "MP-008",
    oem: "T2502179",
    name: "Triumph Street Triple Yağ Filtresi",
    slug: "triumph-street-triple-yag-filtresi",
    description: "Orijinal spesifikasyonda yağ filtresi. Motorunuzu korur.",
    price: 180,
    discountPrice: 149,
    stock: 65,
    images: ["/placeholder.svg?height=400&width=400"],
    brand: brands[7],
    category: categories[5],
    compatibility: [
      { brand: "Triumph", model: "Street Triple", yearStart: 2013, yearEnd: 2023 },
      { brand: "Triumph", model: "Speed Triple", yearStart: 2011, yearEnd: 2023 },
    ],
    weight: 0.15,
    dimensions: { width: 8, height: 8, depth: 10 },
    tags: ["filtre", "yağ filtresi", "triumph"],
    isActive: true,
    isFeatured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

export const mockProducts = products

export const motorcycleModels: Record<string, string[]> = {
  Honda: ["CBR250R", "CBR500R", "CBR600RR", "CBR1000RR", "CB300F", "CB500F", "CB650R", "Africa Twin", "NC750X"],
  Yamaha: ["YZF-R3", "YZF-R6", "YZF-R1", "MT-03", "MT-07", "MT-09", "Tracer 900", "Tenere 700"],
  Suzuki: ["GSX-R600", "GSX-R750", "GSX-R1000", "GSX-S750", "V-Strom 650", "V-Strom 1050"],
  Kawasaki: ["Ninja 400", "Ninja 650", "Ninja ZX-6R", "Ninja ZX-10R", "Z650", "Z900", "Versys 650"],
  BMW: ["G310R", "F750GS", "F850GS", "R1200GS", "R1250GS", "S1000RR", "S1000XR"],
  KTM: ["Duke 200", "Duke 390", "Duke 790", "RC 390", "390 Adventure", "790 Adventure"],
  Ducati: ["Monster 821", "Monster 1200", "Panigale V2", "Panigale V4", "Multistrada 950", "Scrambler"],
  Triumph: ["Street Triple", "Speed Triple", "Tiger 900", "Bonneville T120", "Trident 660"],
}
